import type { PluginDefinition } from "../types";

export const jwtPluginDefinition: PluginDefinition = {
  id: "jwt",
  version: "2.0.0",
  label: "JWT",
  description: "Issue JWTs for stateless API access with configurable JWKS management and payload signing hooks.",
  category: "api",
  documentationUrl: "https://www.better-auth.com/docs/plugins/jwt",
  migrationStrategy: "none",
  dependencies: [],
  requiredEnv: [],
  configSchema: [
    { key: "remoteUrl", label: "Remote JWKS URL", type: "url", helpText: "Disable the local JWKS endpoint and publish this remote URL instead." },
    { key: "disablePrivateKeyEncryption", label: "Disable private key encryption", type: "boolean", helpText: "Store private keys without database encryption.", defaultValue: false },
    { key: "rotationInterval", label: "Rotation interval", type: "number", helpText: "Key rotation interval in seconds." },
    { key: "gracePeriod", label: "Grace period", type: "number", helpText: "JWKS grace period in seconds.", defaultValue: 2592000 },
    { key: "jwksPath", label: "JWKS path", type: "string", helpText: "Override the default `/jwks` endpoint path.", defaultValue: "/jwks" },
    { key: "issuer", label: "JWT issuer", type: "string", helpText: "Issuer claim for generated JWTs." },
    { key: "audience", label: "JWT audience", type: "string", helpText: "Audience claim for generated JWTs." },
    { key: "expirationTime", label: "Expiration time", type: "string", helpText: "Expiration time string like `15m`, `1h`, or `1 day`.", defaultValue: "15m" },
    { key: "disableSettingJwtHeader", label: "Disable JWT header", type: "boolean", helpText: "Do not automatically set JWT headers through middleware.", defaultValue: false },
  ],
  capabilities: [
    {
      key: "core",
      label: "JWT issuance",
      description: "JWT endpoints, JWKS storage, and payload signing hooks.",
      enabledByDefault: true,
      requires: [],
      addsModels: ["jwks"],
      addsClientFeatures: ["jwt"],
      addsServerFeatures: ["jwt issue/verify", "jwks endpoint"],
      addsAdminPanels: ["overview", "keys"],
    },
  ],
  extensionSlots: [
    {
      key: "jwt.definePayload",
      label: "Define JWT payload",
      description: "Bind a function that adds custom claims to the JWT payload.",
      kind: "hook",
      required: false,
      handlerIds: [],
      inputSchema: {
        session: "Better Auth session with user and session objects",
        returns: "custom payload object",
      },
      exampleLanguage: "ts",
      exampleTitle: "Add tenant and role claims",
      exampleDescription: "Use a custom payload function to enrich signed JWTs.",
      exampleCode: `export const defineJwtPayload = {
  id: "custom.defineJwtPayload",
  label: "Define JWT payload",
  description: "Adds app-specific claims to the JWT payload.",
  slotKeys: ["jwt.definePayload"],
  build: () => ({
    id: "custom.defineJwtPayload",
    jwtDefinePayload: async ({ user, session }) => ({
      role: user.role,
      sessionId: session.id,
      tenantId: user.tenantId,
    }),
  }),
};`,
    },
    {
      key: "jwt.getSubject",
      label: "Get JWT subject",
      description: "Bind a function that chooses the JWT `sub` claim.",
      kind: "hook",
      required: false,
      handlerIds: [],
      inputSchema: {
        session: "Better Auth session with user and session objects",
        returns: "subject string",
      },
      exampleLanguage: "ts",
      exampleTitle: "Use a tenant-qualified subject",
      exampleDescription: "Override the default user-id subject when your APIs need a custom format.",
      exampleCode: `export const getJwtSubject = {
  id: "custom.getJwtSubject",
  label: "Get JWT subject",
  description: "Uses a tenant-scoped subject claim.",
  slotKeys: ["jwt.getSubject"],
  build: () => ({
    id: "custom.getJwtSubject",
    jwtGetSubject: async ({ user }) => \`\${user.tenantId}:\${user.id}\`,
  }),
};`,
    },
    {
      key: "jwt.sign",
      label: "Remote JWT signer",
      description: "Bind a custom signer when your JWKS are managed by an external signer or HSM.",
      kind: "hook",
      required: false,
      handlerIds: [],
      inputSchema: {
        payload: "JWT payload object",
        returns: "signed JWT string",
      },
      exampleLanguage: "ts",
      exampleTitle: "Sign JWTs with an external key service",
      exampleDescription: "Use this when your signing keys live outside the database.",
      exampleCode: `export const remoteJwtSigner = {
  id: "custom.remoteJwtSigner",
  label: "Remote JWT signer",
  description: "Delegates JWT signing to an external signing service.",
  slotKeys: ["jwt.sign"],
  build: () => ({
    id: "custom.remoteJwtSigner",
    jwtSign: async (payload) => signWithExternalService(payload),
  }),
};`,
    },
  ],
  models: [
    {
      key: "jwks",
      tableName: "jwks",
      label: "JWKS",
      capabilityKeys: ["core"],
      primaryKey: "id",
      fields: [
        { name: "id", type: "text", nullable: false, unique: true, indexed: true },
        { name: "public_key", type: "text", nullable: false, unique: false, indexed: false },
        { name: "created_at", type: "timestamp", nullable: false, unique: false, indexed: false },
        { name: "expires_at", type: "timestamp", nullable: true, unique: false, indexed: false },
      ],
      description: "JWT signing keys managed by the JWT plugin.",
    },
  ],
  adminPanels: [
    { key: "overview", label: "Overview", description: "Plugin state, docs, and config.", capabilityKeys: ["core"] },
    { key: "keys", label: "JWKS", description: "Signing keys and JWKS provisioning state.", capabilityKeys: ["core"] },
  ],
  examples: [
    {
      key: "client-jwt-session",
      title: "Request a JWT-backed session",
      description: "Use the native Better Auth client once the JWT plugin is enabled.",
      language: "ts",
      audience: "client",
      capabilityKeys: ["core"],
      code: `const session = await client.auth.getSession();
console.log(session);`,
    },
    {
      key: "server-jwt-verify",
      title: "Verify JWTs against the published JWKS",
      description: "Use the published JWKS endpoint when integrating downstream APIs.",
      language: "http",
      audience: "api",
      capabilityKeys: ["core"],
      code: `GET /.well-known/jwks.json
Accept: application/json`,
    },
  ],
  clientNamespaces: ["jwt"],
  serverOperations: ["auth.jwt"],
  defaultConfig: {
    gracePeriod: 2592000,
    jwksPath: "/jwks",
    expirationTime: "15m",
    disableSettingJwtHeader: false,
    disablePrivateKeyEncryption: false,
  },
  defaultCapabilityState: { core: true },
  defaultExtensionBindings: {},
};
