import type { PluginDefinition } from "../types";

export const apiKeyPluginDefinition: PluginDefinition = {
  id: "apiKey",
  version: "2.0.0",
  label: "API Key",
  description: "Issue personal or organization API keys with configurable prefixes, expiration, validation, and rate limiting.",
  category: "api",
  documentationUrl: "https://www.better-auth.com/docs/plugins/api-key",
  migrationStrategy: "sql",
  dependencies: [],
  requiredEnv: [],
  configSchema: [
    { key: "configId", label: "Config ID", type: "string", helpText: "Name for this API-key configuration.", defaultValue: "default" },
    { key: "defaultPrefix", label: "Default prefix", type: "string", helpText: "Prefix prepended to generated API keys." },
    { key: "defaultKeyLength", label: "Default key length", type: "number", helpText: "Generated key length, excluding the prefix.", defaultValue: 64 },
    { key: "maximumPrefixLength", label: "Maximum prefix length", type: "number", helpText: "Maximum allowed prefix length.", defaultValue: 32 },
    { key: "minimumPrefixLength", label: "Minimum prefix length", type: "number", helpText: "Minimum allowed prefix length.", defaultValue: 1 },
    { key: "maximumNameLength", label: "Maximum name length", type: "number", helpText: "Maximum allowed API-key name length.", defaultValue: 32 },
    { key: "minimumNameLength", label: "Minimum name length", type: "number", helpText: "Minimum allowed API-key name length.", defaultValue: 1 },
    { key: "requireName", label: "Require name", type: "boolean", helpText: "Require a human-readable name when creating API keys.", defaultValue: false },
    { key: "enableMetadata", label: "Enable metadata", type: "boolean", helpText: "Allow clients to store metadata on API keys.", defaultValue: false },
    { key: "enableSessionForAPIKeys", label: "Enable session for API keys", type: "boolean", helpText: "Mock Better Auth sessions from valid API keys.", defaultValue: false },
    { key: "disableKeyHashing", label: "Disable key hashing", type: "boolean", helpText: "Store API keys without hashing. Not recommended.", defaultValue: false },
    { key: "defaultExpiresIn", label: "Default expires in", type: "number", helpText: "Default expiration time in milliseconds." },
    { key: "disableCustomExpiresTime", label: "Disable custom expires time", type: "boolean", helpText: "Ignore custom expiration times sent by clients.", defaultValue: false },
    { key: "minExpiresIn", label: "Minimum expires in", type: "number", helpText: "Minimum client-provided expiration in days.", defaultValue: 1 },
    { key: "maxExpiresIn", label: "Maximum expires in", type: "number", helpText: "Maximum client-provided expiration in days.", defaultValue: 365 },
    { key: "rateLimitEnabled", label: "Enable rate limiting", type: "boolean", helpText: "Apply default rate limits to new API keys.", defaultValue: true },
    { key: "rateLimitTimeWindow", label: "Rate limit window", type: "number", helpText: "Rate-limit window in milliseconds.", defaultValue: 86400000 },
    { key: "rateLimitMax", label: "Rate limit max", type: "number", helpText: "Maximum requests allowed within the rate-limit window.", defaultValue: 10 },
    { key: "references", label: "References", type: "string", helpText: "Use `user` or `organization` ownership.", defaultValue: "user" },
    { key: "storage", label: "Storage backend", type: "string", helpText: "Use `database` or `secondary-storage`.", defaultValue: "database" },
    { key: "fallbackToDatabase", label: "Fallback to database", type: "boolean", helpText: "Fallback to database when secondary storage misses.", defaultValue: false },
    { key: "deferUpdates", label: "Defer updates", type: "boolean", helpText: "Defer non-critical counter updates to background tasks.", defaultValue: false },
  ],
  capabilities: [
    {
      key: "core",
      label: "API keys",
      description: "API key issuance, validation, storage, and rate limiting.",
      enabledByDefault: true,
      requires: [],
      addsModels: ["apikey"],
      addsClientFeatures: ["apiKey"],
      addsServerFeatures: ["api key issue/revoke", "api key auth", "api key rate limits"],
      addsAdminPanels: ["overview", "keys", "config"],
    },
  ],
  extensionSlots: [
    {
      key: "apiKey.customAPIKeyGetter",
      label: "Custom API key getter",
      description: "Bind a function that extracts API keys from custom request locations.",
      kind: "hook",
      required: false,
      handlerIds: [],
      inputSchema: {
        ctx: "Better Auth hook context",
        returns: "API key string or null",
      },
      exampleLanguage: "ts",
      exampleTitle: "Read API keys from a cookie",
      exampleDescription: "Use a custom getter when you do not want to read from the default headers.",
      exampleCode: `export const apiKeyGetter = {
  id: "custom.apiKeyGetter",
  label: "Read API keys from cookies",
  description: "Extracts API keys from a custom cookie.",
  slotKeys: ["apiKey.customAPIKeyGetter"],
  build: () => ({
    id: "custom.apiKeyGetter",
    customAPIKeyGetter: (ctx) => getCookieFromContext(ctx, "x_api_key"),
  }),
};`,
    },
    {
      key: "apiKey.customAPIKeyValidator",
      label: "Custom API key validator",
      description: "Bind a function that performs additional API-key validation.",
      kind: "policy",
      required: false,
      handlerIds: [],
      inputSchema: {
        ctx: "Better Auth endpoint context",
        key: "Raw API key string",
        returns: "boolean",
      },
      exampleLanguage: "ts",
      exampleTitle: "Reject API keys outside a maintenance window",
      exampleDescription: "Add environment-aware validation before the key is accepted.",
      exampleCode: `export const apiKeyValidator = {
  id: "custom.apiKeyValidator",
  label: "Validate API keys",
  description: "Applies custom business rules before accepting API keys.",
  slotKeys: ["apiKey.customAPIKeyValidator"],
  build: () => ({
    id: "custom.apiKeyValidator",
    customAPIKeyValidator: async ({ key }) => !key.startsWith("revoked_"),
  }),
};`,
    },
    {
      key: "apiKey.customKeyGenerator",
      label: "Custom key generator",
      description: "Bind a function that generates API keys with a custom format.",
      kind: "hook",
      required: false,
      handlerIds: [],
      inputSchema: {
        length: "Requested key length",
        prefix: "Configured key prefix",
        returns: "generated API key string",
      },
      exampleLanguage: "ts",
      exampleTitle: "Generate ULID-based API keys",
      exampleDescription: "Override the default random generator if you need a custom key format.",
      exampleCode: `export const apiKeyGenerator = {
  id: "custom.apiKeyGenerator",
  label: "Generate API keys",
  description: "Creates API keys using a custom key format.",
  slotKeys: ["apiKey.customKeyGenerator"],
  build: () => ({
    id: "custom.apiKeyGenerator",
    customKeyGenerator: async ({ prefix }) => \`\${prefix ?? "ak_"}\${generateUlid()}\`,
  }),
};`,
    },
    {
      key: "apiKey.defaultPermissions",
      label: "Default permissions",
      description: "Bind a function that assigns default permissions to new API keys.",
      kind: "hook",
      required: false,
      handlerIds: [],
      inputSchema: {
        referenceId: "Owner user or organization id",
        ctx: "Better Auth endpoint context",
        returns: "permission statements",
      },
      exampleLanguage: "ts",
      exampleTitle: "Assign read-only permissions by default",
      exampleDescription: "Set default permissions when new API keys are created.",
      exampleCode: `export const defaultApiKeyPermissions = {
  id: "custom.defaultApiKeyPermissions",
  label: "Default API key permissions",
  description: "Adds read-only permissions to newly created API keys.",
  slotKeys: ["apiKey.defaultPermissions"],
  build: () => ({
    id: "custom.defaultApiKeyPermissions",
    defaultPermissions: async () => ({
      project: ["read"],
    }),
  }),
};`,
    },
  ],
  models: [
    {
      key: "apikey",
      tableName: "apikey",
      label: "API keys",
      capabilityKeys: ["core"],
      primaryKey: "id",
      fields: [
        { name: "id", type: "text", nullable: false, unique: true, indexed: true },
        { name: "config_id", type: "text", nullable: false, unique: false, indexed: true },
        { name: "name", type: "text", nullable: true, unique: false, indexed: false },
        { name: "start", type: "text", nullable: true, unique: false, indexed: false },
        { name: "reference_id", type: "text", nullable: false, unique: false, indexed: true },
        { name: "prefix", type: "text", nullable: true, unique: false, indexed: false },
        { name: "refill_interval", type: "integer", nullable: true, unique: false, indexed: false },
        { name: "refill_amount", type: "integer", nullable: true, unique: false, indexed: false },
        { name: "last_refill_at", type: "timestamp", nullable: true, unique: false, indexed: false },
        { name: "enabled", type: "boolean", nullable: false, unique: false, indexed: false },
        { name: "rate_limit_enabled", type: "boolean", nullable: false, unique: false, indexed: false },
        { name: "rate_limit_time_window", type: "integer", nullable: true, unique: false, indexed: false },
        { name: "rate_limit_max", type: "integer", nullable: true, unique: false, indexed: false },
        { name: "request_count", type: "integer", nullable: false, unique: false, indexed: false },
        { name: "remaining", type: "integer", nullable: true, unique: false, indexed: false },
        { name: "last_request", type: "timestamp", nullable: true, unique: false, indexed: false },
        { name: "expires_at", type: "timestamp", nullable: true, unique: false, indexed: false },
        { name: "permissions", type: "text", nullable: true, unique: false, indexed: false },
        { name: "metadata", type: "text", nullable: true, unique: false, indexed: false },
        { name: "created_at", type: "timestamp", nullable: false, unique: false, indexed: false },
        { name: "updated_at", type: "timestamp", nullable: false, unique: false, indexed: false },
      ],
      description: "Issued API keys and their usage metadata.",
    },
  ],
  adminPanels: [
    { key: "overview", label: "Overview", description: "Plugin state, docs, and diagnostics.", capabilityKeys: ["core"] },
    { key: "keys", label: "Issued keys", description: "Operational view of issued API keys.", capabilityKeys: ["core"] },
    { key: "config", label: "Config", description: "Prefix, expiration, storage, and rate-limit settings.", capabilityKeys: ["core"] },
  ],
  examples: [
    {
      key: "client-create-api-key",
      title: "Create an API key",
      description: "Issue an API key once the plugin is enabled.",
      language: "ts",
      audience: "client",
      capabilityKeys: ["core"],
      code: `await client.auth.apiKey.create({
  name: "CI token",
});`,
    },
    {
      key: "client-list-api-keys",
      title: "List issued API keys",
      description: "Read API keys through the Better Auth client namespace.",
      language: "ts",
      audience: "client",
      capabilityKeys: ["core"],
      code: `const keys = await client.auth.apiKey.list();`,
    },
  ],
  clientNamespaces: ["apiKey"],
  serverOperations: ["auth.apiKey"],
  defaultConfig: {
    configId: "default",
    defaultKeyLength: 64,
    maximumPrefixLength: 32,
    minimumPrefixLength: 1,
    maximumNameLength: 32,
    minimumNameLength: 1,
    requireName: false,
    enableMetadata: false,
    enableSessionForAPIKeys: false,
    disableKeyHashing: false,
    disableCustomExpiresTime: false,
    minExpiresIn: 1,
    maxExpiresIn: 365,
    rateLimitEnabled: true,
    rateLimitTimeWindow: 86400000,
    rateLimitMax: 10,
    references: "user",
    storage: "database",
    fallbackToDatabase: false,
    deferUpdates: false,
  },
  defaultCapabilityState: { core: true },
  defaultExtensionBindings: {},
};
