export const SYSTEM_TABLES = [
  '_plugin_configs',
  '_migration_runs',
  '_audit_logs',
  '_system_settings',
  '_backup_runs',
  '_cron_jobs',
  '_cron_runs',
  '_ai_threads',
  '_ai_messages',
  '_ai_runs',
  '_storage_files',
  '_system_admins',
  '_schema_tables',
  '_schema_fields',
  '_schema_relations',
];
