import type { PluginDefinition } from "../types";

export const usernamePluginDefinition: PluginDefinition = {
  id: "username",
  version: "2.0.0",
  label: "Username",
  description: "Allow unique usernames on top of email and password auth with custom validation and normalization.",
  category: "authentication",
  documentationUrl: "https://www.better-auth.com/docs/plugins/username",
  migrationStrategy: "none",
  dependencies: [],
  requiredEnv: [],
  configSchema: [
    {
      key: "minUsernameLength",
      label: "Minimum username length",
      type: "number",
      helpText: "Minimum allowed username length.",
      defaultValue: 3,
    },
    {
      key: "maxUsernameLength",
      label: "Maximum username length",
      type: "number",
      helpText: "Maximum allowed username length.",
      defaultValue: 30,
    },
    {
      key: "usernameValidationOrder",
      label: "Username validation order",
      type: "string",
      helpText: "Use `pre-normalization` or `post-normalization`.",
      defaultValue: "pre-normalization",
    },
    {
      key: "displayUsernameValidationOrder",
      label: "Display username validation order",
      type: "string",
      helpText: "Use `pre-normalization` or `post-normalization`.",
      defaultValue: "pre-normalization",
    },
  ],
  capabilities: [
    {
      key: "core",
      label: "Username support",
      description: "Adds username fields, username sign-in, and availability checks.",
      enabledByDefault: true,
      requires: [],
      addsModels: [],
      addsClientFeatures: ["username"],
      addsServerFeatures: ["username sign-in", "username availability"],
      addsAdminPanels: ["overview", "settings"],
    },
  ],
  extensionSlots: [
    {
      key: "usernameValidator",
      label: "Username validator",
      description: "Bind a custom function to validate usernames.",
      kind: "policy",
      required: false,
      defaultHandlerId: "authend.defaultUsernameValidator",
      handlerIds: [],
      inputSchema: {
        username: "Candidate username string",
        returns: "boolean",
      },
      exampleLanguage: "ts",
      exampleTitle: "Allow only workspace-style handles",
      exampleDescription: "Create a custom validator and register it from `plugins/extensions/index.ts`.",
      exampleCode: `export const workspaceUsernameValidator = {
  id: "custom.workspaceUsernameValidator",
  label: "Workspace username validator",
  description: "Accepts lowercase letters, numbers, underscores, and dots.",
  slotKeys: ["usernameValidator"],
  build: () => ({
    id: "custom.workspaceUsernameValidator",
    usernameValidator: (username) => /^[a-z0-9_.]+$/.test(username),
  }),
};`,
    },
    {
      key: "displayUsernameValidator",
      label: "Display username validator",
      description: "Bind a custom function to validate display usernames.",
      kind: "policy",
      required: false,
      handlerIds: [],
      inputSchema: {
        displayUsername: "Visible username string",
        returns: "boolean",
      },
      exampleLanguage: "ts",
      exampleTitle: "Limit display username length",
      exampleDescription: "Add a custom validator if your display usernames need additional checks.",
      exampleCode: `export const displayUsernameValidator = {
  id: "custom.displayUsernameValidator",
  label: "Display username validator",
  description: "Rejects overly long display usernames.",
  slotKeys: ["displayUsernameValidator"],
  build: () => ({
    id: "custom.displayUsernameValidator",
    displayUsernameValidator: (displayUsername) => displayUsername.trim().length <= 48,
  }),
};`,
    },
    {
      key: "usernameNormalization",
      label: "Username normalization",
      description: "Bind a custom function to normalize usernames before persistence.",
      kind: "hook",
      required: false,
      defaultHandlerId: "authend.lowercaseUsernameNormalization",
      handlerIds: [],
      inputSchema: {
        username: "Candidate username string",
        returns: "normalized username string",
      },
      exampleLanguage: "ts",
      exampleTitle: "Normalize usernames to kebab-like handles",
      exampleDescription: "Use a custom normalizer if the default lowercase behavior is not enough.",
      exampleCode: `export const normalizeUsername = {
  id: "custom.normalizeUsername",
  label: "Normalize username",
  description: "Trims, lowercases, and replaces spaces with underscores.",
  slotKeys: ["usernameNormalization"],
  build: () => ({
    id: "custom.normalizeUsername",
    usernameNormalization: (username) => username.trim().toLowerCase().replace(/\\s+/g, "_"),
  }),
};`,
    },
    {
      key: "displayUsernameNormalization",
      label: "Display username normalization",
      description: "Bind a custom function to normalize display usernames before persistence.",
      kind: "hook",
      required: false,
      defaultHandlerId: "authend.identityDisplayUsernameNormalization",
      handlerIds: [],
      inputSchema: {
        displayUsername: "Visible username string",
        returns: "normalized display username string",
      },
      exampleLanguage: "ts",
      exampleTitle: "Trim display usernames",
      exampleDescription: "Keep user-visible casing while trimming extra whitespace.",
      exampleCode: `export const normalizeDisplayUsername = {
  id: "custom.normalizeDisplayUsername",
  label: "Normalize display username",
  description: "Trims whitespace but keeps the original casing.",
  slotKeys: ["displayUsernameNormalization"],
  build: () => ({
    id: "custom.normalizeDisplayUsername",
    displayUsernameNormalization: (displayUsername) => displayUsername.trim(),
  }),
};`,
    },
  ],
  models: [],
  adminPanels: [
    {
      key: "overview",
      label: "Overview",
      description: "Plugin state, examples, and docs.",
      capabilityKeys: ["core"],
    },
    {
      key: "settings",
      label: "Settings",
      description: "Validation, normalization, and runtime config.",
      capabilityKeys: ["core"],
    },
  ],
  examples: [
    {
      key: "client-sign-up-username",
      title: "Sign up with a username",
      description: "The username plugin extends email/password sign-up with a username field.",
      language: "ts",
      audience: "client",
      capabilityKeys: ["core"],
      code: `await client.auth.signUp.email({
  email: "dev@example.com",
  password: "ChangeMe123!",
  name: "Dev User",
  username: "devuser",
});`,
    },
    {
      key: "client-sign-in-username",
      title: "Sign in with a username",
      description: "Use the native Better Auth username client methods once the plugin is enabled.",
      language: "ts",
      audience: "client",
      capabilityKeys: ["core"],
      code: `await client.auth.signIn.username({
  username: "devuser",
  password: "ChangeMe123!",
});`,
    },
    {
      key: "client-check-username",
      title: "Check username availability",
      description: "Validate a candidate username before sign-up.",
      language: "ts",
      audience: "client",
      capabilityKeys: ["core"],
      code: `const result = await client.auth.username.isUsernameAvailable({
  username: "devuser",
});`,
    },
  ],
  clientNamespaces: ["username"],
  serverOperations: ["auth.username"],
  defaultConfig: {
    minUsernameLength: 3,
    maxUsernameLength: 30,
    usernameValidationOrder: "pre-normalization",
    displayUsernameValidationOrder: "pre-normalization",
  },
  defaultCapabilityState: { core: true },
  defaultExtensionBindings: {
    usernameValidator: "authend.defaultUsernameValidator",
    usernameNormalization: "authend.lowercaseUsernameNormalization",
    displayUsernameNormalization: "authend.identityDisplayUsernameNormalization",
  },
  getRollbackPlan: () => ({
    key: "plugin_username_v1",
    title: "Disable username plugin",
    sql: `update "user"
set "username" = null,
    "display_username" = null,
    "updated_at" = now()
where "username" is not null
   or "display_username" is not null;`,
  }),
};
